project:
  type: website
  output-dir: docs
  
resources:
  - "cv/cornforthc_biostats_cv.pdf"

website:
  title: "Cornforth \nePortfolio"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "About Me"
        href: about.qmd
      - text: "Research Interests"
        href: research-interests.qmd
      - text: "Curriculum Vitae"
        href: cv/cv.qmd
      - text: "Class Projects"
        menu:
          - text: "Project: Exploring Seabird Data"
            href: portfolio-project/project-portfolio.qmd
      - text: "Blog"
        href: blog.qmd

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: source